Repository wecode-bootcamp-korea/19-1st-greatingdor-frontend, pull requests merged in 2021-04, with the labels that each got.

#2 [19기 이명진] Feature/main
  package-lock.json
  public/data/cardList.json
  public/data/img/1.jpg
  public/data/img/2.jpg
  public/data/img/3.jpg
  public/data/img/4.jpg
  src/Pages/Main/AdBanner/AdBanner.js
  src/Pages/Main/AdBanner/AdBanner.scss
  src/Pages/Main/Card/Card.js
  src/Pages/Main/Card/Card.scss
  src/Pages/Main/Filter/Category.js
  src/Pages/Main/Filter/Category.scss
  src/Pages/Main/Filter/Filter.js
  src/Pages/Main/Filter/Filter.scss
  src/Pages/Main/Main.js
  src/Pages/Main/Main.scss
  src/Pages/Main/Option/Option.js
  src/Pages/Main/Option/Option.scss
  src/Pages/Main/PageHandler/PageHandler.js
  src/Pages/Main/PageHandler/PageHandler.scss
  src/Styles/common.scss
  src/index.js
Labels: Status: 리뷰 요청

#4 [19기 박세리] 로그인 페이지 1차 리뷰 반영
  .eslintrc
  src/Components/SnsWrap/SnsWrap.js
  src/Components/SnsWrap/SnsWrap.scss
  src/Img/icon-google.png
  src/Img/icon-kakao.png
  src/Img/icon-naver.png
  src/Pages/Login/Login.js
  src/Pages/Login/Login.scss
  src/Pages/Login/login.scss
  src/Pages/ProductDetail/ProductDetail.js
  src/Pages/ProductDetail/ProductDetail.scss
  src/Pages/SignUp/SignUp.js
  src/Pages/SignUp/SignUp.scss
  src/Routes.js
  src/Styles/common.scss
  src/Styles/reset.scss
Labels: Status: Conflict 발생

#6 [19기 박세리] 회원가입 페이지 담당 Feature/sign up
  src/Components/SnsWrap/SnsWrap.scss
  src/Img/greatingdor-logo.jpg
  src/Img/hpoint-logo.jpg
  src/Pages/Cart/Cart.js
  src/Pages/Login/Login.js
  src/Pages/Login/login.scss
  src/Pages/SignUp/SignUp.js
  src/Pages/SignUp/SignUp.scss
  src/Pages/SignUpDetail/SignUpDetail.js
  src/Pages/SignUpDetail/SignUpDetail.scss
  src/Routes.js
  src/index.js
Labels: Status: Conflict 발생

#8 [19기 이명진] main페이지 CSS 수정입니다
  src/Pages/Main/Card/Card.js
  src/Pages/Main/Card/Card.scss
  src/Pages/Main/Main.js
  src/Styles/common.scss
Labels: Status: Merge 요청

#5 [19기 박성은] Conflict 해결
  public/data/cartData.json
  public/data/inquiryTab.json
  public/data/productData.json
  public/data/productInfoImage.json
  public/data/reviewTab.json
  public/images/1.jpg
  public/images/2.jpg
  public/images/3.jpg
  src/Pages/ProductDetail/Location/Location.js
  src/Pages/ProductDetail/Location/Location.scss
  src/Pages/ProductDetail/ProductDescription/ExchangeRefundTab/ExchangeRefundTab.js
  src/Pages/ProductDetail/ProductDescription/ExchangeRefundTab/ExchangeRefundTab.scss
  src/Pages/ProductDetail/ProductDescription/InformationTab/InformationTab.js
  src/Pages/ProductDetail/ProductDescription/InformationTab/InformationTab.scss
  src/Pages/ProductDetail/ProductDescription/InquiryTab/InquiryTab.js
  src/Pages/ProductDetail/ProductDescription/InquiryTab/InquiryTab.scss
  src/Pages/ProductDetail/ProductDescription/ProductDescription.js
  src/Pages/ProductDetail/ProductDescription/ProductDescription.scss
  src/Pages/ProductDetail/ProductDescription/ReviewTab/DropDown/DropDown.js
  src/Pages/ProductDetail/ProductDescription/ReviewTab/DropDown/DropDown.scss
  src/Pages/ProductDetail/ProductDescription/ReviewTab/ReviewTab.js
  src/Pages/ProductDetail/ProductDescription/ReviewTab/ReviewTab.scss
  src/Pages/ProductDetail/ProductDetail.js
  src/Pages/ProductDetail/ProductDetail.scss
  src/Pages/ProductDetail/ProductInfo/CartModal/CartModal.js
  src/Pages/ProductDetail/ProductInfo/CartModal/CartModal.scss
  src/Pages/ProductDetail/ProductInfo/ImageSlider/ImageSlider.js
  src/Pages/ProductDetail/ProductInfo/ImageSlider/ImageSlider.scss
  src/Pages/ProductDetail/ProductInfo/ProductInfo.js
  src/Pages/ProductDetail/ProductInfo/ProductInfo.scss
  src/Pages/ProductDetail/ProductInfo/ProductMetaData/ProductMetaData.js
  src/Pages/ProductDetail/ProductInfo/ProductMetaData/ProductMetaData.scss
  src/Routes.js
  yarn.lock
Labels: Status: Conflict 발생, Status: 추가 기능 구현중

#1 [19기 박성은] Navbar : 2차 리뷰 반영
  public/data/CustomerCenter.json
  public/data/MenuItems.json
  public/data/SearchItems.json
  public/img/img_header_logo_Greating.png
  src/Components/NavBar/CategoryDropDown/CategoryDropDown.js
  src/Components/NavBar/CategoryDropDown/CategoryDropDown.scss
  src/Components/NavBar/NavBar.js
  src/Components/NavBar/NavBar.scss
  src/Components/NavBar/SearchDropDown/Button/Button.js
  src/Components/NavBar/SearchDropDown/Button/Button.scss
  src/Components/NavBar/SearchDropDown/SearchDropDown.js
  src/Components/NavBar/SearchDropDown/SearchDropDown.scss
  src/Pages/Login/Login.js
  src/Pages/Login/Login.scss
  src/Pages/ProductDetail/ProductDetail.js
  src/Pages/SignUp/SignUp.js
  src/Styles/common.scss
  yarn.lock
Labels: Status: 수정 요청, Status: 추가 기능 구현중
